apps/accounts/urls.py
from pathlib import Path

from django.urls import path

from . import views

app_name = 'accounts'

urlpatterns = [
    path('novo-usuario/', views.add_user, name='add_user'),
    path('login/', views.login_user, name='login_user'),
    path('alterar-senha/', views.password_change_user, name='password_change_user'),
    path('novo-perfil/', views.add_profile_user, name='add_profile_user'),
    path('meu-perfil/', views.list_profile_user, name='list_profile_user'),
    path('aletrar-perfil/<username>/', views.change_profile_user, name='change_profile_user'),
    path('aletrar-usuario/<username>/', views.change_information_user, name='change_information_user'),
    path('sair/', views.logout_user, name='logout_user'),
]

django_fandre/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core')),
    path('tarefas/', include('tasks.urls', namespace='tasks')),
    path('contas/', include('accounts.urls', namespace='accounts')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
#urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

apps/accounts/models.py
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.db import models


class UserProfile(models.Model):
    photo = models.ImageField('Foto', upload_to='photos')
    cell_phone = models.CharField('Celular', max_length=16)
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile')

    class Meta:
        verbose_name = 'Perfil do usuário'
        verbose_name_plural = 'Perfis do usuários'
    
    def __str__(self):
        return self.user.username
    
    def clean(self):
        model = self.__class__
        if model.objects.count() > 0 and self.id != model.objects.get().id:
            raise ValidationError("Vocẽ ja possui um perfil cadastrado.")

apps/accounts/forms.py
from django import forms
from django.contrib.auth.models import User

from .models import UserProfile


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'username', 'password', 'email']
        #fields = '__all__' tras todos os campos da model user

class UserFormChangeInformation(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email']

class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        exclude = ['user']

apps/accounts/views.py
from django.contrib import messages
from django.contrib.auth import (authenticate, login, logout,
                                 update_session_auth_hash)
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.models import User
from django.shortcuts import redirect, render

from .forms import UserForm, UserFormChangeInformation, UserProfileForm
from .models import UserProfile


def add_user(request):
    template_name = 'accounts/add_user.html'
    context = {}
    if request.method == 'POST':
        form = UserForm(request.POST)
        if form.is_valid():
            f = form.save(commit=False)
            f.set_password(f.password)
            f.save()
            messages.success(request, 'Usuário salvo com sucesso!')
    form = UserForm()
    context['form'] = form
    return render(request, template_name, context)


def login_user(request):
    template_name = 'accounts/login_user.html'

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect(request.GET.get('next', '/'))
        else:
            messages.error(request, 'Usuário ou senha incorretos.')
    return render(request, template_name, {})


@login_required(login_url='contas/login/')
def logout_user(request):
    logout(request)
    return redirect('accounts:login_user')


@login_required(login_url='contas/login/')
def password_change_user(request):
    template_name = 'accounts/password_change_user.html'
    context = {}
    if request.method == 'POST':
        form = PasswordChangeForm(user=request.user, data=request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, "Senha atualizada com sucesso.")
            update_session_auth_hash(request, form.user)
        else:
            messages.error(request, "Não foi possível atualaizar a senha!")
    form = PasswordChangeForm(user=request.user)
    context['form'] = form
    return render(request, template_name, context)

@login_required(login_url='contas/login')
def add_profile_user(request):
    template_name = 'accounts/add_profile_user.html'
    context = {}
    if request.method == 'POST':
        form = UserProfileForm(request.POST, request.FILES)
        if form.is_valid():
            f = form.save(commit=False)
            f.user = request.user
            f.save()
            messages.success(request, "Perfil alterado como sucesso!")
    form = UserProfileForm()
    context['form'] = form
    return render(request, template_name, context)


@login_required(login_url='contas/login')
def list_profile_user(request):
    template_nome = 'accounts/list_profile.html'
    try:
        profile = UserProfile.objects.get(user=request.user)
    except UserProfile.DoesNotExist:
        profile = None
    context ={
        'profile': profile
    }    
    return render(request, template_nome, context)


@login_required(login_url='contas/login')
def change_profile_user(request, username):
    template_name = 'accounts/add_profile_user.html'
    context = {}
    profile = UserProfile.objects.get(user__username=username) # __ lookup
    if request.method == 'POST':
        form = UserProfileForm(request.POST, request.FILES, instance=profile)
        if form.is_valid():
            form.save()
            messages.success(request, 'Perfil atualizado com sucesso.')
    form = UserProfileForm(instance=profile)
    context['form'] = form
    return render(request, template_name, context)


@login_required(login_url='contas/login')
def change_information_user(request, username):
    template_name = 'accounts/change_information_user.html'
    context = {}
    user = User.objects.get(username=username)
    if request.method == 'POST':
        form = UserFormChangeInformation(request.POST, instance=user)
        if form.is_valid():
            form.save()
            messages.success(request, "Informações atualizadas com sucesso.")
    form = UserFormChangeInformation(instance=user)
    context['form'] = form
    return render(request, template_name, context)

templates/accounts/add_profile_user.html
{% extends 'base.html' %}

{% load widget_tweaks %}

{% block title %}
    Atualizar perfil - {{ block.super }}
{% endblock title %}


{% block body %}

<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h1>Atualizar perfil</h1>
            {% include 'partials/messages.html' %}
            <form action="." method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form-group">
                    <label for="{{ form.photo.id_for_label }}">Foto do perfil</label>
                    {{ form.photo|add_class:"form-control-file" }}
                </div>
                <div class="form-group">
                    <label for="{{ form.cell_phone.id_for_label }}">Celular</label>
                    {{ form.cell_phone|add_class:"form-control"|attr:"autofocus" }}
                </div>
                <button type="submit" class="btn btn-primary">Salvar</button>
              </form>
        </div>
    </div>
</div>

{% endblock body %}

templates/accounts/add_user.html
{% extends 'base.html' %}

{% load widget_tweaks %}

{% block title %}
    Novo Usuário - {{ block.super }}
{% endblock title %}


{% block body %}

<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h1>Novo Usuário</h1>
            {% include 'partials/messages.html' %}
            <form action="." method="POST">
                {% csrf_token %}                
                <div class="form-group">
                    <label for="{{ form.first_name.id_for_label }}">Primeiro Nome</label>
                    {{ form.first_name|add_class:"form-control"|attr:"autofocus" }}
                </div>
                <div class="form-group">
                    <label for="{{ form.last_name.id_for_label }}">Sobrenome</label>
                    {{ form.last_name|add_class:"form-control" }}
                </div>
                <div class="form-group">
                    <label for="{{ form.username.id_for_label }}">Nome de Usuário</label>
                    {{ form.username|add_class:"form-control" }}
                </div>
                <div class="form-group">
                    <label for="{{ form.email.id_for_label }}">E-mail</label>
                    {{ form.email|add_class:"form-control "}}
                </div>
                <div class="form-group">
                    <label for="{{ form.password.id_for_label }}">Senha</label>
                    {{ form.password|add_class:"form-control"|attr:"type:password" }}
                </div>
                <button type="submit" class="btn btn-primary">Salvar</button>
              </form>
        </div>
    </div>
</div>

{% endblock body %}

templates/accounts/change_information_user.html
{% extends 'base.html' %}

{% load widget_tweaks %}

{% block title %}
    Atualizar Usuário - {{ block.super }}
{% endblock title %}


{% block body %}

<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h1>Atualizar Usuário</h1>
            {% include 'partials/messages.html' %}
            <form action="." method="POST">
                {% csrf_token %}                
                <div class="form-group">
                    <label for="{{ form.first_name.id_for_label }}">Primeiro Nome</label>
                    {{ form.first_name|add_class:"form-control"|attr:"autofocus" }}
                </div>
                <div class="form-group">
                    <label for="{{ form.last_name.id_for_label }}">Sobrenome</label>
                    {{ form.last_name|add_class:"form-control" }}
                </div>
                <div class="form-group">
                    <label for="{{ form.email.id_for_label }}">E-mail</label>
                    {{ form.email|add_class:"form-control "}}
                </div>
                <button type="submit" class="btn btn-primary">Salvar</button>
              </form>
        </div>
    </div>
</div>

{% endblock body %}

templates/accounts/list_profile.html
{% extends 'base.html' %}

{% load staticfiles %}

{% load widget_tweaks %}

{% block title %}
    Meu Perfil - {{ block.super }}
{% endblock title %}


{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h1>Meu Perfil</h1>
            {% if profile %}
                <div class="media">
                    <img src="{{ profile.photo.url }}" class="align-self-start mr-3 rounded-circle" alt="" widht="100" height="100">
                    <div class="media-body">
                        <h5 class="mt-0">{{ profile.user.get_full_name }}</h5>
                        <p>Celular: {{ profile.cell_phone }}</p>
                        <p>E-mail: {{ profile.user.email }}</p>
                    </div>
                </div>
                    <a href="{% url 'accounts:change_profile_user' user.username %}" class="btn btn-primary">Alterar Perfil</a>                
            {% else %}
                    <h2>Vocẽ não criou um perfil.</h2>
                    <a href="{% url 'accounts:add_profile_user' %}" class="btn btn-primary">Criar Perfil</a>
            {% endif %}
        </div>
    </div>
</div>

{% endblock body %}

templates/accounts/login_user.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/signin.css' %}">    
    <title>Tasks - Login</title>
</head>
<body class="text-center">    
    <form class="form-signin" method="POST" action=".">
        {% csrf_token %}
        <h1 class="h3 mb-3 font-weight-normal">Identifique-se</h1>
        <label for="username" class="sr-only">Usuário</label>
        <input type="text" id="username" name="username" class="form-control" placeholder="Nome de usuário." required autofocus>
        <br>
        <label for="inputPassword" class="sr-only">Senha</label>
        <input type="password" id="password" name="password" class="form-control" placeholder="Digite sua senha." required>
        <button class="btn btn-lg btn-primary btn-block" type="submit">Entrar</button>
        <a href="{% url 'accounts:add_user' %}"  class="btn btn-lg btn-secondary btn-block" type="submit">Registre-se</a>
      </form>

      <script src="{% static 'js/jquery-3.6.0.slim.js' %}"></script>
      <script src="{% static 'js/bootstrap.js' %}"></script>    
  
</body>
</html>

templates/accounts/password_change_user.html
{% extends 'base.html' %}

{% load widget_tweaks %}

{% block title %}
    Atualização de senha - {{ block.super }}
{% endblock title %}


{% block body %}

<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h1>Atualização de senha</h1>
            {% include 'partials/messages.html' %}
            <form action="." method="POST">
                {% csrf_token %}                
                <div class="form-group">
                    <label for="{{ form.old_password.id_for_label }}">Senha atual</label>
                    {{ form.old_password|add_class:"form-control"|attr:"autofocus"|attr:"type:password" }}
                </div>
                <div class="form-group">
                    <label for="{{ form.new_password1.id_for_label }}">Nova senha</label>
                    {{ form.new_password1|add_class:"form-control"|attr:"type:password" }}
                </div>
                <div class="form-group">
                    <label for="{{ form.new_password2.id_for_label }}">Confirme nova senha</label>
                    {{ form.new_password2|add_class:"form-control"|attr:"type:password" }}
                </div>
                <button type="submit" class="btn btn-primary">Atualizar</button>
              </form>
        </div>
    </div>
</div>

{% endblock body %}