apps/accounts/urls.py
from pathlib import Path

from django.urls import path

from . import views

app_name = 'accounts'

urlpatterns = [
    path('novo-usuario/', views.add_user, name='add_user'),
    path('login/', views.login_user, name='login_user'),
    path('alterar-senha/', views.password_change_user, name='password_change_user'),
    path('novo-perfil/', views.add_profile_user, name='add_profile_user'),
    path('meu-perfil/', views.list_profile_user, name='list_profile_user'),
    path('aletrar-perfil/<username>/', views.change_profile_user, name='change_profile_user'),
    path('aletrar-usuario/<username>/', views.change_information_user, name='change_information_user'),
    path('sair/', views.logout_user, name='logout_user'),
]

apps/core/urls.py
from django.urls import path

from . import views

app_name = 'core'

urlpatterns = [    
    path('', views.home, name='home'),
    path('pesquisar/', views.search_tasks, name='search_tasks'),
]

apps/tasks/urls.py
from django.urls import path

from . import views

app_name = 'tasks'

urlpatterns = [
    # URLs Categorias
    path('categorias', views.list_categories, name='list_categories'),
    path('categorias/adicionar/', views.add_category, name='add_category'),
    path('categorias/editar/<int:id_category>/', views.edit_category, name='edit_category'),
    path('categorias/excluir/<int:id_category>/', views.delete_category, name='delete_category'),
    # URLs Tarefas
    path('', views.list_tasks, name='list_tasks'),
    path('adicionar/', views.add_task, name='add_task'),
    path('editar/<int:id_task>/', views.edit_task, name='edit_task'),
    path('excluir/<int:id_task>/', views.delete_task, name='delete_task'),
]

django_fandre/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core')),
    path('tarefas/', include('tasks.urls', namespace='tasks')),
    path('contas/', include('accounts.urls', namespace='accounts')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
#urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

apps/tasks/models.py
from django.contrib.auth.models import User
from django.db import models


class Category(models.Model):
    name = models.CharField('Nome', max_length=150)
    description = models.TextField('Descrição', blank=True, null=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'Categoria'
        verbose_name_plural = 'Categorias'
        ordering = ['id']
    
    def __str__(self):
        return self.name


class Task(models.Model):
    PRIORITY_CHOICES = (
        ('B', 'Baixa'),
        ('M', 'Média'),
        ('A', 'Alta'),
    )
    STATUS_CHOICES = (
        ('EX','Em execução'),
        ('PD','Pendente'),
        ('CD','Concluída'),
    )

    name = models.CharField('Tarefa', max_length=200)
    description = models.TextField('Descrição')
    end_date = models.DateField('Data Final', auto_now=False, auto_now_add=False)
    priority = models.CharField('Prioridade', max_length=1, choices=PRIORITY_CHOICES)
    category = models.ManyToManyField(Category)
    status = models.CharField('Status', max_length=2, choices=STATUS_CHOICES)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    
    class Meta:
        verbose_name = 'Tarefa'
        verbose_name_plural = 'Tarefas'
        ordering = ['id']

    def __str__(self):
        return self.name

    def list_categories(self):
        return ", ".join([c.name for c in self.category.all()])
    list_categories.short_description = "Categorias"

templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/select2.css' %}">
    <link rel="stylesheet" href="//code.jquery.com/ui/1.13.1/themes/base/jquery-ui.css">
    <link rel="stylesheet" href="/resources/demos/style.css">
    <title>{% block title %}Django - Francisco Andre - Udemy{% endblock title %}</title>
</head>
<body>

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand" href="/">TasksApp</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample07" aria-controls="navbarsExample07" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>      
          <div class="collapse navbar-collapse" id="navbarsExample07">
            <ul class="navbar-nav mr-auto">
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="dropdown07" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Menu</a>
                <div class="dropdown-menu" aria-labelledby="dropdown07">
                  <a class="dropdown-item" href="{% url 'tasks:add_category' %}">Adicionar categoria</a>
                  <a class="dropdown-item" href="{% url 'tasks:list_categories' %}">Listar categorias</a>
                  <a class="dropdown-item" href="{% url 'tasks:add_task' %}">Adicionar tarefa</a>
                  <a class="dropdown-item" href="{% url 'tasks:list_tasks' %}">Listar tarefas</a>
                </div>
              </li>
            </ul>
            <form class="form-inline my-2 my-md-0" action="{% url 'core:search_tasks' %}" style="margin-right:10px" autocomplete="off" style="magin-right:10px">
              <input class="form-control" name="query" type="text" placeholder="Digite o termo da busca" aria-label="Search" style="margin-right:10px">
              <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Pesquisar</button>
            </form>
            {% if user.is_authenticated %}
            <ul class="navbar-nav">
              <li class="nav-item">
                {% if user.profile.photo %}
                  <img src="{{ user.profile.photo.url }}" class="rounded-circle" width="40" height="40">
                {% else %}
                  <img src="{% static 'img/user_defualt.png' %}" class="rounded-circle" width="40" height="40">
                {% endif %}
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="dropdown07" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">{{ user.username }}</a> <!-- user.get_full_name|default:user.username -->
                <div class="dropdown-menu" aria-labelledby="dropdown07">
                  <a class="dropdown-item" href="{% url 'accounts:list_profile_user' %}">Perfil</a>
                  <a class="dropdown-item" href="{% url 'accounts:change_information_user' user.username %}">Dados</a>
                  <a class="dropdown-item" href="{% url 'accounts:password_change_user' %}">Trocar senha</a>
                  <a class="dropdown-item" href="{% url 'accounts:logout_user' %}">Sair</a>                  
                </div>
              </li>
            </ul>
            {% endif %}
          </div>
        </div>
      </nav>
      

    {% block body %}

    {% endblock body %}

    <!-- O Bootstrap possui uma dependência: jQuery. Incluir o código da biblioteca antes de incluir o arquivo bootstrap.js -->
    
    <script src="{% static 'js/jquery-3.6.0.slim.js' %}"></script>
    <script src="{% static 'js/bootstrap.js' %}"></script>    
    <script src="{% static 'js/jquery-3.6.0.js' %}"></script>
    <script src="https://code.jquery.com/ui/1.13.1/jquery-ui.js"></script>
    <script src="{% static 'js/select2.js' %}"></script>
    <script src="{% static 'js/jquery.mask.js' %}"></script>
    <script src="{% static 'js/mask.js' %}"></script>    
    <script>
      $(document).on('click', '.confirm-delete', function() {
        $('#confirmDeleteModal').attr('caller-id', $(this).attr('id'));
      });
      $(document).on('click', '#confirmDeleteButtonModal', function() {
        var caller = $('#confirmDeleteButtonModal').closest('.modal').attr('caller-id');
        window.location = $('#'.concat(caller)).attr('href');
      });
      $( function() {
        $( '#id_end_date' ).datepicker(
          {
            dateFormat: "dd/mm/yy",
            dayNamesMin: ["Dom", "Seg", "Ter", "Qua", "Qui", "Sex", "Sáb"],
            monthNames: ["Janeiro", "Fevereiro", "Março", "Abril", "Maio", "Junho", "Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro"],
          }
        );
      } );
      $(document).ready(function() {
        $('#id_category').select2();
      });
    </script>  
    
</body>
</html>